### ISSUE TITLE
Popover and tooltip positioning problem in firefox

### ISSUE THREAD

**Issue by ricsv** [ricsv/react-leonardo-ui#3]
When the page has a scroll, popovers and tooltips will position themselves without compensating for the scroll amount.

Easily seen on the documentation page.

**Comment by stoffeastrom** [comment]
I think you can use `window.pageXOffset` and `window.pageYOffset`instead. If you want to use `scrollLeft` `scrollTop` you need to get the 'correct' scrolling element e.g

```
document.scrollingElement || document.documentElement || document.body;
```

**Comment by ricsv** [comment]
@stoffeastrom Worked like a charm, thanks!
