### ISSUE TITLE
Test all components

### ISSUE THREAD

**Issue by ricsv** [ricsv/react-leonardo-ui#4]
Add tests for the components:

- Dialog
- Popover
- Tooltip
- Search

Currently, they are not tested because tests are run in a NodeJS environment and these components are using the `document`, `window` or an `HTMLElement`.

Should investigate if it's possible to run these tests in a jsdom environment (https://github.com/facebook/jest/tree/master/packages/jest-environment-jsdom).

**Comment by stoffeastrom** [comment]
I don't know about jest but I've successfully used `jsdom` with Mocha!

**Comment by ricsv** [comment]
Fixed by https://github.com/ricsv/react-leonardo-ui/pull/25 and recent commits on master
