### ISSUE TITLE
export `default`

### ISSUE THREAD

**Issue by stoffeastrom** [ricsv/react-leonardo-ui#5]
Is there any reason why you use `export default Button` and then the re-export

`export { default as Button } from './button';` ?

**Comment by ricsv** [comment]
You mean in `index.js` files?

Yes, it's a coding convention I'm following (https://github.com/airbnb/javascript#modules--no-export-from-import). I know the file `react-leonardo-ui.js` violates this, will fix it soon.

**Comment by ricsv** [comment]
Closing this issue referring to the changes in https://github.com/ricsv/react-leonardo-ui/pull/7
